### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by king-anduin** [ONLYOFFICE/CommunityServer#267]
Hi guys, 
I hope someone can help me out here. I use CommunityServer with a docker-compose script.

```
version: '3'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=XXX
     - MYSQL_DATABASE=onlyoffice
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
     - ./mysql/mysql/initdb:/docker-entrypoint-initdb.d
  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:11.0.0.1458
    depends_on:
     - onlyoffice-mysql-server
     - onlyoffice-document-server
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - CONTROL_PANEL_PORT_80_TCP=80
     - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - DOCUMENT_SERVER_JWT_ENABLED=true
     - DOCUMENT_SERVER_JWT_SECRET=jwt_secret
     - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
     - MYSQL_SERVER_ROOT_PASSWORD=XXX
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass
    networks:
     - onlyoffice
    ports:
     - '100:80'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    volumes:
     - ./CommunityServer/data:/var/www/onlyoffice/Data
     - ./CommunityServer/logs:/var/log/onlyoffice
     - ./CommunityServer/letsencrypt:/etc/letsencrypt
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:6.0.2
    stdin_open: true
    tty: true
    restart: always
    environment:
     - JWT_ENABLED=true
     - JWT_SECRET=jwt_secret
     - JWT_HEADER=AuthorizationJwt
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
       - ./DocumentServer/data:/var/www/onlyoffice/Data
       - ./DocumentServer/logs:/var/log/onlyoffice
       - ./DocumentServer/fonts:/usr/share/fonts/truetype/custom
       - ./DocumentServer/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    depends_on:
     - onlyoffice-document-server
     - onlyoffice-community-server
    image: onlyoffice/controlpanel:2.9.0.351
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
    expose:
      - '80'
      - '443'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ControlPanel/data:/var/www/onlyoffice/Data
      - ./ControlPanel/logs:/var/log/onlyoffice
    networks:
      - onlyoffice
    stdin_open: true
    tty: true
networks:
  onlyoffice:
    driver: 'bridge'`
```
It started and it seems to work but if I try to log in, I get an internal server error 500.
I checked database and it worked with root access and PW.

![Screenshot from 2020-12-21 22-00-52](https://user-images.githubusercontent.com/56738872/102821867-2c4a5d00-43d8-11eb-8ce5-be9ae7522ffa.png)

Strange thing is right after installation I could access to document server but right after supervisorctl start ds:example my acces was gone. I just gut Internal error 500.
