### ISSUE TITLE
 can't run on rocky linux

### ISSUE THREAD

**Issue by anyu-svg** [ONLYOFFICE/CommunityServer#509]
## Question Discreption
this same docker-compose.yml can run on a ubuntu but can't run on rocky linux,  
i try this docker-compose file on about 4 rocky linux mechine, but can't run success. No obvious error messages
i can't find the reason. 

```
# i add the rabbitmq container because the document inner rabbitmq is start slow.
version: '3'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:8.0.29
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - ./config/mysql/conf.d:/etc/mysql/conf.d
     - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - mysql_data:/var/lib/mysql
  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:latest
    depends_on:
     - onlyoffice-mysql-server
     - onlyoffice-document-server
     - onlyoffice-elasticsearch
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - CONTROL_PANEL_PORT_80_TCP=80
     - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - DOCUMENT_SERVER_JWT_ENABLED=true
     - DOCUMENT_SERVER_JWT_SECRET=jwt_secret
     - DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass
     - ELASTICSEARCH_SERVER_HOST=onlyoffice-elasticsearch
     - ELASTICSEARCH_SERVER_HTTPPORT=9200
    networks:
     - onlyoffice
    ports:
     - '8080:80'
     - '8443:443'
     - '15222:5222'
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    cgroup: host
    volumes:
     - community_data:/var/www/onlyoffice/Data
     - community_log:/var/log/onlyoffice
     - community_letsencrypt:/etc/letsencrypt
     - document_data:/var/www/onlyoffice/DocumentServerData
     - /sys/fs/cgroup:/sys/fs/cgroup:rw
     - ./certs:/var/www/onlyoffice/Data/certs
  onlyoffice-elasticsearch:
    image: onlyoffice/elasticsearch:7.16.3
    container_name: onlyoffice-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      - "indices.fielddata.cache.size=30%"
      - "indices.memory.index_buffer_size=30%" 
      - "ingest.geoip.downloader.enabled=false"
    networks:
    - onlyoffice    
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    depends_on:
     - rabbitmq
    environment:
     - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
     - JWT_ENABLED=true
     - JWT_SECRET=jwt_secret
     - JWT_HEADER=AuthorizationJwt
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
       - document_data:/var/www/onlyoffice/Data
       - document_log:/var/log/onlyoffice
       - document_fonts:/usr/share/fonts/truetype/custom
       - document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    depends_on:
     - onlyoffice-document-server
     - onlyoffice-community-server
    image: onlyoffice/controlpanel:3.1.1.467
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
    expose:
      - '80'
      - '443'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - controlpanel_data:/var/www/onlyoffice/Data
      - controlpanel_log:/var/log/onlyoffice
    networks:
      - onlyoffice
    stdin_open: true
    tty: true
  rabbitmq:
    image: rabbitmq:latest
    container_name: onlyoffice-rabbitmq
    restart: unless-stopped
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
      - 'rabbitmq_plugins:/plugins'
      - 'rabbitmq_config:/etc/rabbitmq/conf.d'
    networks:
      - onlyoffice
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_fonts:
  document_log:
  document_forgotten:
  community_mysql:
  community_data:
  community_log:
  community_letsencrypt:
  controlpanel_data:
  controlpanel_log:
  mysql_data:
  es_data:
  rabbitmq_data:
  rabbitmq_plugins:
  rabbitmq_config:
```

this is the documentserver log

```
onlyoffice-document-server  | Generating WOPI private key...Done
onlyoffice-document-server  | Generating WOPI public key...Done
onlyoffice-document-server  |  * Starting PostgreSQL 14 database server  [ OK ] 
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | Waiting for connection to the onlyoffice-rabbitmq host on port 5672
onlyoffice-document-server  | psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:4: NOTICE:  table "doc_callbacks" does not exist, skipping
onlyoffice-document-server  | psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:9: NOTICE:  function merge_db(pg_catalog.varchar,int2,int8,pg_catalog.timestamp,pg_catalog.varchar,int8,int8) does not exist, skipping
onlyoffice-document-server  | psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:10: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,pg_catalog.varchar,int4,int4) does not exist, skipping
onlyoffice-document-server  | psql:/var/www/onlyoffice/documentserver/server/schema/postgresql/removetbl.sql:11: NOTICE:  function merge_db(pg_catalog.varchar,int2,int4,pg_catalog.timestamp,int4,int4,text,text) does not exist, skipping
onlyoffice-document-server  | Starting supervisor: supervisord.
onlyoffice-document-server  |  * Starting periodic command scheduler cron[ OK ] 
onlyoffice-document-server  |  * Starting nginx nginx                    [ OK ] 
onlyoffice-document-server  | Generating AllFonts.js, please wait...Done
onlyoffice-document-server  | Generating presentation themes, please wait...Done
onlyoffice-document-server  | Generating js caches, please wait...Done
onlyoffice-document-server  | ds:docservice: stopped
onlyoffice-document-server  | ds:docservice: started
onlyoffice-document-server  | ds:converter: stopped
onlyoffice-document-server  | ds:converter: started
onlyoffice-document-server  |  * Reloading nginx configuration nginx     [ OK ] 
onlyoffice-document-server  | 
onlyoffice-document-server  | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
onlyoffice-document-server  | 
onlyoffice-document-server  | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
onlyoffice-document-server  | [2024-07-26T08:12:24.949] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
onlyoffice-document-server  | [2024-07-26T08:12:24.952] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-document-server  | [2024-07-26T08:12:24.968] [WARN] [localhost] [docId] [userId] nodeJS - worker 602 started.
onlyoffice-document-server  | [2024-07-26T08:12:24.981] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
onlyoffice-document-server  | [2024-07-26T08:12:24.981] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-document-server  | [2024-07-26T08:13:35.389] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
onlyoffice-document-server  | [2024-07-26T08:13:35.393] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-document-server  | [2024-07-26T08:13:35.414] [WARN] [localhost] [docId] [userId] nodeJS - worker 708 started.
onlyoffice-document-server  | [2024-07-26T08:13:35.420] [WARN] [localhost] [docId] [userId] nodeJS - num of CPUs: 4; availableParallelism: undefined
onlyoffice-document-server  | [2024-07-26T08:13:35.421] [WARN] [localhost] [docId] [userId] nodeJS - update cluster with 1 workers
onlyoffice-document-server  | 
onlyoffice-document-server  | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
onlyoffice-document-server  | 
onlyoffice-document-server  | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice-document-server  | [2024-07-26T08:12:27.626] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-document-server  | [2024-07-26T08:12:27.646] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
onlyoffice-document-server  | [2024-07-26T08:12:27.977] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 8.1.1. Build: 26
onlyoffice-document-server  | [2024-07-26T08:13:35.227] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
onlyoffice-document-server  | [2024-07-26T08:13:35.232] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
onlyoffice-document-server  | [2024-07-26T08:13:35.501] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 8.1.1. Build: 26
onlyoffice-document-server  | 
onlyoffice-document-server  | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
```

OS Infomation
my ubuntu22.04 is 8 core 16RAM x84_64;
my rockylinux9.4 is 8 core 16RAM x86_64, i just installed 24 July.

Docker infomation
```
Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:04:07 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:31 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Docker Compose version v2.28.1
```
